function plotSingleReconstruction( reconVals, mu, ntypes, filename, savefig )

idx1 = 1;
idx2 = 2;

x0 = 0;
y0 = 0;
width = 5;
height = 4;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');

plot( reconVals( idx1), reconVals( idx2),...
        'o', "Color", "r" )
hold on

for distVal = 1:ntypes

    colorval = [ rand(), rand(), rand() ];

    plot( mu( distVal, idx1 ), mu( distVal, idx2 ), "x", "Color", colorval )
    hold on;
end

xlabel('{\boldmath$X$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('{\boldmath$Y$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

if(savefig)
    print( fig1, filename, '-depsc2' );
end

end