function plotDataDistribution( data, N, filename )

x0 = 0;
y0 = 0;
width = 7;
height = 6;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');

for distVal = 1:N
    colorval = [ 1, rand(), rand() ];

    plot( data( distVal: N : end, 1), data( distVal: N : end, 2),...
        '.', "Color", colorval )
    hold on;
end

xlabel('{\boldmath$X$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('{\boldmath$Y$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

print( fig1, filename, '-depsc2' );

end