function plotPerfData( dataArr, filename )

nOptions = size( dataArr, 1 );

x0 = 0;
y0 = 0;
width = 7;
height = 6;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');

for iopt = 1:nOptions

    plot( dataArr( iopt, : ) )
    hold on;
end

legend({"sqp", "interior-point", "custom solver"})

xlabel('{\boldmath$Test Data Samples$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('{\boldmath$Function Evaluations$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

print( fig1, filename, '-depsc2' );
end