function plotKPCAParaError( paraVals, errorVals, filename )

x0 = 0;
y0 = 0;
width = 7;
height = 6;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');

plot( paraVals, errorVals, 'ro-' )

xlabel('{\boldmath$\sigma$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('Denoising Error',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

print( fig1, filename, '-depsc2' );

end