function plotContours( X, Y, Z, data, Yvals, idx, filename, withScatter, nlevels )

x0 = 0;
y0 = 0;
width = 5;
height = 4;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');

contour( X, Y, Z, nlevels )
colorbar;

if( withScatter )
    hold on
    scatter( data(:, 1), data(:, 2), 10, Yvals(:, idx) );
end

xlabel('{\boldmath$X$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('{\boldmath$Y$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

print( fig1, filename, '-depsc2' );

end