function plotReconstructions( reconVals, mu, filename, ntypes, withMu, savefig, varargin )

idx1 = 1;
idx2 = 2;

if nargin == 5
    idx1 = 1;
    idx2 = 2;
end

x0 = 0;
y0 = 0;
width = 5;
height = 4;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');


for distVal = 1 : ntypes

    colorval = [ rand(), rand(), rand() ];
    
    plot( reconVals( distVal: ntypes : end, idx1), reconVals( distVal: ntypes : end, idx2),...
        'o', "Color", colorval )

    hold on
    if( withMu )
        plot( mu( distVal, idx1 ), mu( distVal, idx2 ), "x", "Color", colorval )
    end 
   hold on;
end

xlabel('{\boldmath$X$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('{\boldmath$Y$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

if(savefig)
    print( fig1, filename, '-depsc2' );
end

end