function plotReconstructionObjective( y, X, eigVector, d, para, valsRange, filename, ktype )

Nsamples = size( X, 1 );
gamma=zeros(1, Nsamples);

for j = 1:Nsamples
    gamma(j) = eigVector(j, 1:d) * y;
end

objFunc = @(x, y)projectionObjective2D( x, y, gamma, X, para, ktype );

x0 = 0;
y0 = 0;
width = 7;
height = 6;

fig1 = figure('Units','inches',...
        'Position',[x0 y0 width height],...
        'PaperPositionMode','auto');
set(gca,...
    'Units','normalized',...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Times');

fsurf( objFunc, valsRange )
colorbar()

xlabel('{\boldmath$X$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

ylabel('{\boldmath$Y$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

zlabel('{\boldmath$\rho(z)$}',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontSize',9,...
    'Interpreter', 'latex',...
    'FontName','Times');

print( fig1, filename, '-depsc2' );
end